apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-platform
  namespace: gitlab
spec:
  secretName: gitlab-platform-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: gitlab.platform.glslinc.com
  dnsNames:
    - gitlab.platform.glslinc.com
    - reg.gitlab.platform.glslinc.com
  